name = "capture-screenshot-sending-discord"
main = "src/index.ts"
compatibility_date = "2025-03-05"
compatibility_flags = ["nodejs_compat_v2"]

# Browser binding
[browser]
binding = "BROWSER"

# Environment variables
[vars]
# TARGET_URL = "your-target-url-here"
# DISCORD_BOT_TOKEN = "your-discord-bot-token-here"  
# DISCORD_CHANNEL_ID = "your-discord-channel-id-here"

# Cron trigger - runs every Friday at 15:00 JST (06:00 UTC)
[triggers]
crons = ["0 6 * * 5"]

[observability.logs]
enabled = true